CREATE TABLE `booking` (
  `IDBOOKING` int(11) NOT NULL AUTO_INCREMENT,
  `BOOKINGDATE` datetime NOT NULL,
  `IDCLIENT` int(11) NOT NULL,
  `IDPARKINGPLACE` int(11) NOT NULL,
  `IDVEHICLE` int(11) NOT NULL,
  PRIMARY KEY (`IDBOOKING`),
  KEY `FK_PARKING_PLACE_1_idx` (`IDPARKINGPLACE`),
  KEY `FK_CLIENT_1_idx` (`IDCLIENT`),
  KEY `FK_VEHICLE_1_idx` (`IDVEHICLE`),
  CONSTRAINT `FK_CLIENT_1` FOREIGN KEY (`IDCLIENT`) REFERENCES `client` (`IDCLIENT`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_PARKING_PLACE_1` FOREIGN KEY (`IDPARKINGPLACE`) REFERENCES `parkingplace` (`IDPARKINGPLACE`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_VEHICLE_1` FOREIGN KEY (`IDVEHICLE`) REFERENCES `vehicle` (`IDVEHICLE`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `client` (
  `IDCLIENT` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `NIF` varchar(255) NOT NULL,
  `SURNAME` varchar(255) NOT NULL,
  `TELEPHONE` varchar(255) NOT NULL,
  PRIMARY KEY (`IDCLIENT`)
) ENGINE=InnoDB AUTO_INCREMENT=636 DEFAULT CHARSET=utf8;

CREATE TABLE `parkingplace` (
  `IDPARKINGPLACE` int(11) NOT NULL AUTO_INCREMENT,
  `PARKINGNUMBER` int(11) NOT NULL,
  `PARKINGPRIZE` double NOT NULL,
  `PARKINGSIZE` double NOT NULL,
  `PARKINGSTATE` tinyint(4) NOT NULL,
  PRIMARY KEY (`IDPARKINGPLACE`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `vehicle` (
  `IDVEHICLE` int(11) NOT NULL AUTO_INCREMENT,
  `VEHICLEMODEL` varchar(255) NOT NULL,
  `VEHICLEPLATE` varchar(255) NOT NULL,
  `IDCLIENT` int(11) NOT NULL,
  PRIMARY KEY (`IDVEHICLE`),
  KEY `FK_VEHICLE_CLIENT_idx` (`IDCLIENT`),
  CONSTRAINT `FK_VEHICLE_CLIENT` FOREIGN KEY (`IDCLIENT`) REFERENCES `client` (`IDCLIENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8;
