
package com.everis.beca.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorImpl", targetNamespace = "http://ws.beca.everis.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorImpl {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns com.everis.beca.ws.CalculationResult
     */
    @WebMethod
    @WebResult(name = "addReturn", targetNamespace = "http://ws.beca.everis.com")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.beca.everis.com", className = "com.everis.beca.ws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.beca.everis.com", className = "com.everis.beca.ws.AddResponse")
    public CalculationResult add(
        @WebParam(name = "a", targetNamespace = "http://ws.beca.everis.com")
        double a,
        @WebParam(name = "b", targetNamespace = "http://ws.beca.everis.com")
        double b);

}
